services:
  - type: web
    name: SecurePass-Bot
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:bot
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: worker
    name: Invite-Checker-Bot
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:invite
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
